/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "EvonyBackend": {
      "type": "sst.aws.Service"
      "url": string
    }
    "archiveBuild": {
      "ArchivePaths": any
      "buildResult": string
      "commit": string
      "sha": string
      "type": "sst.sst.Linkable"
    }
  }
}
