/* This file is auto-generated by SST. Do not edit. */

import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "EvonyBackend": {
      "type": "sst.aws.Service"
      "url": string
    }
  }
}
