const fileDebug: Record<string, boolean> = {
  "assets/collections/art/collection.ts": false,
  "assets/collections/ascendingAttributes/collection.ts": false,
  "assets/collections/blazons/collection.ts": false,
  "assets/collections/buff/collection.ts": false,
  "assets/collections/covenants/collection.ts": false,
  "assets/collections/generalConflictGroups/collection.ts": false,
  "assets/collections/generals/collection.ts": false,
  "assets/collections/skillBooks/collection.ts": false,
  "assets/collections/specialities/collection.ts": false,
  "components/CardGrid.ts": false,
  "components/SplashCards.ts": false,
  "components/TopHeader.ts": false,
  "components/generals/pairing/debugStores.ts": false,
  "components/generals/pairing/generalPairing.ts": false,
  "components/generals/pairing/pairingstores.ts": false,
  "components/generals/pairing/selector.ts": false,
  "components/Monsters/Simulator/BuffTable.ts": true,
  "components/Monsters/Simulator/MarchTable.ts": true,
  "components/Monsters/Simulator/MonsterOrder.ts": true,
  "components/Monsters/Simulator/reference.ts": true,
  "components/Monsters/Simulator/state.ts": true,
  "components/sidebar.ts": false,
  "components/theme.ts": false,
  "layouts/general.ts": false,
  "layouts/standard.ts": false,
  "lib/collections/ascendingAttributes.ts": false,
  "lib/collections/generals.ts": false,
  "lib/collections/skillBooks.ts": false,
  "lib/collections/specialities.ts": false,
  "lib/debug.ts": false,
  "lib/greenwoodPages.ts": false,
  "lib/topLevelSections.ts": false,
  "pages/Generals/details/index.ts": false,
  "pages/Generals/pair-picking.ts": false,
  "pages/api/collections/generals.ts": false,
  "schemas/art.ts": false,
  "schemas/ascending.ts": false,
  "schemas/blazons.ts": false,
  "schemas/buff.ts": false,
  "schemas/cardMetaData.ts": false,
  "schemas/constants.ts": false,
  "schemas/covenants.ts": false,
  "schemas/generalConflictGroups.ts": false,
  "schemas/generals.ts": false,
  "schemas/skillBooks.ts": false,
  "schemas/specialities.ts": false,
  "schemas/table.ts": false,
};

const debugFunction = (myName: string): boolean => {
  return fileDebug[myName];
};

export default debugFunction;
