import { z } from "zod";
import { GeneralPair } from "./generals";

export const TableColumns = z.object({
  level: z.boolean(),
  PvM_attack_total: z.boolean(),
  PvM_attack_totalAttribute: z.boolean(),
  PvM_attack_BaseSkill: z.boolean(),
  PvM_attack_SkillBooks: z.boolean(),
  PvM_attack_Speciality1: z.boolean(),
  PvM_attack_Speciality2: z.boolean(),
  PvM_attack_Speciality3: z.boolean(),
  PvM_attack_Speciality4: z.boolean(),
  PvM_attack_Ascending: z.boolean(),
  PvM_defense_total: z.boolean(),
  PvM_defense_totalAttribute: z.boolean(),
  PvM_defense_BaseSkill: z.boolean(),
  PvM_defense_SkillBooks: z.boolean(),
  PvM_defense_Speciality1: z.boolean(),
  PvM_defense_Speciality2: z.boolean(),
  PvM_defense_Speciality3: z.boolean(),
  PvM_defense_Speciality4: z.boolean(),
  PvM_defense_Ascending: z.boolean(),
  PvM_hp_total: z.boolean(),
  PvM_hp_totalAttribute: z.boolean(),
  PvM_hp_BaseSkill: z.boolean(),
  PvM_hp_SkillBooks: z.boolean(),
  PvM_hp_Speciality1: z.boolean(),
  PvM_hp_Speciality2: z.boolean(),
  PvM_hp_Speciality3: z.boolean(),
  PvM_hp_Speciality4: z.boolean(),
  PvM_hp_Ascending: z.boolean(),
  PvM_doubleDrop_total: z.boolean(),
  PvM_doubleDrop_totalAttribute: z.boolean(),
  PvM_doubleDrop_BaseSkill: z.boolean(),
  PvM_doubleDrop_SkillBooks: z.boolean(),
  PvM_doubleDrop_Speciality1: z.boolean(),
  PvM_doubleDrop_Speciality2: z.boolean(),
  PvM_doubleDrop_Speciality3: z.boolean(),
  PvM_doubleDrop_Speciality4: z.boolean(),
  PvM_doubleDrop_Ascending: z.boolean(),
});
export type TableColumns = z.infer<typeof TableColumns>;
