const fileDebug: Record<string, boolean> = {
  "components/generals/GeneralOptions/GeneralOptions.ts": false,
  "components/generals/GeneralOptions/store.ts": false,
  "components/generals/PairingTable.ts": false,
  "components/generals/PvP/Attacking/debuff.ts": false,
  "components/generals/PvP/Attacking/specialities.ts": false,
  "components/generals/TableSorting.ts": false,
  "components/generals/ValueSelector.ts": false,
  "components/generals/backendTable.ts": false,
  "components/generals/columns.ts": false,
  "components/generals/general.ts": false,
  "components/generals/generics/EvAnsScore.ts": false,
  "components/generals/generics/genericAscending.ts": false,
  "components/generals/generics/genericBook.ts": false,
  "components/generals/generics/genericBuff.ts": false,
  "components/generals/generics/genericSpecialities.ts": false,
  "components/generals/generics/genericStandardSkillBook.ts": false,
  "components/generals/store.ts": false,
  "components/generals/visibility/attacking.ts": false,
  "components/generals/visibility/default.ts": false,
  "components/generals/visibility/pvm.ts": false,
  "content.config.ts": false,
  "content/art/collection.ts": false,
  "content/ascendingAttributes/collection.ts": false,
  "content/blazons/collection.ts": false,
  "content/buff/collection.ts": false,
  "content/covenants/collection.ts": false,
  "content/generalConflictGroups/collection.ts": false,
  "content/generals/collection.ts": false,
  "content/skillBooks/collection.ts": false,
  "content/specialities/collection.ts": false,
  "debug.ts": false,
  "lib/rallySpot.ts": false,
  "lib/standardSkillBooks.ts": false,
  "lib/topLevelSections.ts": false,
  "lib/uuidBase.ts": false,
  "schemas/art.ts": false,
  "schemas/ascending.ts": false,
  "schemas/blazons.ts": false,
  "schemas/buff.ts": false,
  "schemas/constants.ts": false,
  "schemas/covenants.ts": false,
  "schemas/generalConflictGroups.ts": false,
  "schemas/generals.ts": false,
  "schemas/skillBooks.ts": false,
  "schemas/specialities.ts": false,
  "schemas/table.ts": false,
};

const DEBUG = (myName: string): boolean => {
  return fileDebug[myName];
};

export default DEBUG;
